# Generated by Django 5.2.3 on 2025-06-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indeed_Scrapper_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField()),
                ('job_urls', models.TextField()),
                ('ignore_companies', models.TextField(blank=True, null=True)),
                ('jobs_per_company', models.IntegerField(blank=True, null=True)),
                ('max_items', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
